services:
  backdrop:
    image: backdrop:latest
    container_name: backdrop
    ports:
      - 8088:80
    environment:
      BACKDROP_DB_HOST: database.mydomain.com
      BACKDROP_DB_USER: backdropuser
      BACKDROP_DB_PASSWORD: changeme
